# Generated by Django 4.0.8 on 2024-05-07 16:52

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Ticket',
            fields=[
                ('ticket_id', models.AutoField(primary_key=True, serialize=False)),
                ('date_purchase', models.DateTimeField(default=django.utils.timezone.now)),
                ('duration', models.IntegerField(default=3600)),
            ],
        ),
        migrations.CreateModel(
            name='VisitorProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('login', models.CharField(max_length=128)),
                ('password', models.CharField(max_length=128)),
            ],
        ),
        migrations.CreateModel(
            name='Zone',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=128)),
                ('description', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='TicketZone',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ticket_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='zooland.ticket')),
                ('zone_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='zooland.zone')),
            ],
        ),
        migrations.AddField(
            model_name='ticket',
            name='visitor_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='zooland.visitorprofile'),
        ),
    ]
