# Generated by Django 4.0 on 2024-05-08 10:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('zooland', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticket',
            name='zones',
            field=models.ManyToManyField(to='zooland.Zone'),
        ),
    ]
