# Generated by Django 4.0 on 2024-05-08 12:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('zooland', '0002_ticket_zones'),
    ]

    operations = [
        migrations.DeleteModel(
            name='TicketZone',
        ),
    ]
